<?php 

function popcorn_menu(){
  $items['popcorn/%'] = array(
    'page callback' => '_popcorn_load_node',
    'access arguments' => array('access content'),
    'page arguments' => array(1, 2),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function _popcorn_load_node($nid, $type = 'full'){
  $node = node_load($nid);
  switch ($type){
    case 'teaser':
      $output = drupal_render(node_view($node, $type));
      break;
    case 'full':
      if ($node->type == 'film_clip'){
        
      }
      else{
        $output = drupal_render(node_view($node, $type));
      }
      break;
    case 'kernels':
      $output = "This is where node event data will be returned";
      if ($node->type == 'film_clip'){
        $kernels = array();
        foreach ($node->field_events['und'] as $index => $kernel){
          $kernels[$index] = array(
            'start' => $index * 5,
            'end' => $index * 5 + 20,
            'nid' => $kernel['nid']
          );
        }
        $output = drupal_json_encode($kernels);
      }
      break;
    default:
      $output = drupal_render(node_view($node, $type));
  }
  print $output;
  exit();
}

function popcorn_node_view_alter(&$build) {
  if (isset($build['links']['node']['#links']['node-readmore']['title'])) {
    $build['links']['node']['#links']['node-readmore']['title'] = 'Read more...';
  }
}
