<?php 

function popcorn_menu(){
  $items['popcorn/%'] = array(
    'page callback' => '_popcorn_load_node',
    'access arguments' => array('access content'),
    'page arguments' => array(1, 2),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function _popcorn_load_node($nid, $type = 'full'){
  print drupal_render(node_view(node_load($nid), $type));
  exit();
}

function popcorn_node_view_alter(&$build) {
  if (isset($build['links']['node']['#links']['node-readmore']['title'])) {
    $build['links']['node']['#links']['node-readmore']['title'] = 'Read more...';
  }
}
